package models

import "encoding/json"

type Meeting struct {
	ConferenceOpenVideo                          *bool
	MotionsShowSequentialNumber                  *bool
	PollDefaultGroupIDs                          []int
	UsersEmailSubject                            *string
	UsersForbidDelegatorAsSupporter              *bool
	ConferenceShow                               *bool
	UsersEmailReplyto                            *string
	MotionPollDefaultGroupIDs                    []int
	CommitteeID                                  int
	JitsiDomain                                  *string
	MotionsExportSubmitterRecommendation         *bool
	StructureLevelListOfSpeakersIDs              []int
	AgendaNumberPrefix                           *string
	FontProjectorH1ID                            *int
	ListOfSpeakersAllowMultipleSpeakers          *bool
	MotionsNumberType                            *string
	MotionsNumberWithBlank                       *bool
	UsersForbidDelegatorAsSubmitter              *bool
	UsersForbidDelegatorInListOfSpeakers         *bool
	ListOfSpeakersEnablePointOfOrderSpeakers     *bool
	LogoPdfHeaderLID                             *int
	MotionBlockIDs                               []int
	MotionsDefaultStatuteAmendmentWorkflowID     int
	PresentUserIDs                               []int
	TopicPollDefaultGroupIDs                     []int
	DefaultProjectorMediafileIDs                 []int
	ExportPdfPageMarginRight                     *int
	ID                                           *int
	Language                                     string
	UsersPdfWlanEncryption                       *string
	MotionsEnableRecommendationOnProjector       *bool
	AgendaShowTopicNavigationOnDetailView        *bool
	DefaultGroupID                               int
	Location                                     *string
	MotionIDs                                    []int
	MotionPollDefaultType                        *string
	AssignmentCandidateIDs                       []int
	ListOfSpeakersCountdownID                    *int
	SpeakerIDs                                   []int
	PollDefaultMethod                            *string
	PollDefaultType                              *string
	ApplauseShowLevel                            *bool
	ApplauseType                                 *string
	ConferenceStreamUrl                          *string
	ListOfSpeakersHideContributionCount          *bool
	MotionsDefaultAmendmentWorkflowID            int
	MotionsEnableWorkingGroupSpeaker             *bool
	ExportPdfLineHeight                          *float32
	ListOfSpeakersEnablePointOfOrderCategories   *bool
	MeetingMediafileIDs                          []int
	PollCountdownID                              *int
	TemplateForOrganizationID                    *int
	ApplauseMaxAmount                            *int
	FontMonospaceID                              *int
	MotionPollDefaultMethod                      *string
	StartTime                                    *int
	ApplauseMinAmount                            *int
	ListOfSpeakersCanCreatePointOfOrderForOthers *bool
	MotionsRecommendationTextMode                *string
	ProjectorCountdownWarningTime                int
	AssignmentPollBallotPaperSelection           *string
	PollCoupleCountdown                          *bool
	WelcomeTitle                                 *string
	ApplauseParticleImageUrl                     *string
	DefaultProjectorTopicIDs                     []int
	Description                                  *string
	FontChyronSpeakerNameID                      *int
	AssignmentPollDefaultMethod                  *string
	DefaultProjectorAssignmentIDs                []int
	ExportPdfPagesize                            *string
	DefaultProjectorMotionPollIDs                []int
	MotionPollBallotPaperNumber                  *int
	TagIDs                                       []int
	UsersPdfWlanPassword                         *string
	AgendaItemCreation                           *string
	FontRegularID                                *int
	LogoPdfBallotPaperID                         *int
	MotionsExportTitle                           *string
	MotionsNumberMinDigits                       *int
	ProjectionIDs                                []int
	AssignmentPollDefaultGroupIDs                []int
	ExportPdfFontsize                            *int
	ListOfSpeakersEnableInterposedQuestion       *bool
	MotionsStatuteRecommendationsBy              *string
	PollSortPollResultByVotes                    *bool
	ListOfSpeakersInterventionTime               *int
	MotionsAmendmentsInMainList                  *bool
	MotionsExportFollowRecommendation            *bool
	AgendaEnableNumbering                        *bool
	LockedFromInside                             *bool
	LogoPdfFooterRID                             *int
	MotionWorkflowIDs                            []int
	AssignmentPollSortPollResultByVotes          *bool
	DefaultProjectorListOfSpeakersIDs            []int
	StructureLevelIDs                            []int
	ListOfSpeakersAmountNextOnProjector          *int
	MediafileIDs                                 []int
	PollCandidateListIDs                         []int
	ConferenceAutoConnectNextSpeakers            *int
	ListOfSpeakersInitiallyClosed                *bool
	LogoPdfFooterLID                             *int
	PollDefaultBackend                           *string
	WelcomeText                                  *string
	AnonymousGroupID                             *int
	ListOfSpeakersSpeakerNoteForEveryone         *bool
	MotionsDefaultLineNumbering                  *string
	ListOfSpeakersCoupleCountdown                *bool
	ListOfSpeakersIDs                            []int
	ListOfSpeakersShowFirstContribution          *bool
	DefaultProjectorCurrentListOfSpeakersIDs     []int
	MotionsEnableTextOnProjector                 *bool
	JitsiRoomName                                *string
	AgendaShowInternalItemsOnProjector           *bool
	AssignmentIDs                                []int
	AssignmentPollDefaultOnehundredPercentBase   *string
	IsArchivedInOrganizationID                   *int
	MotionStateIDs                               []int
	ReferenceProjectorID                         int
	ExportPdfPageMarginTop                       *int
	PollIDs                                      []int
	UsersEnablePresenceView                      *bool
	UsersEnableVoteDelegations                   *bool
	UsersEnableVoteWeight                        *bool
	FontBoldID                                   *int
	AgendaNewItemsDefaultVisibility              *string
	ListOfSpeakersCanSetContributionSelf         *bool
	MotionStatuteParagraphIDs                    []int
	MotionsBlockSlideColumns                     *int
	OptionIDs                                    []int
	DefaultProjectorMotionIDs                    []int
	MotionsExportPreamble                        *string
	MotionsStatutesEnabled                       *bool
	PointOfOrderCategoryIDs                      []int
	UsersEmailSender                             *string
	VoteIDs                                      []int
	AssignmentPollAddCandidatesToListOfSpeakers  *bool
	FontProjectorH2ID                            *int
	LogoProjectorHeaderID                        *int
	MotionPollDefaultBackend                     *string
	MotionWorkingGroupSpeakerIDs                 []int
	PollBallotPaperNumber                        *int
	AllProjectionIDs                             []int
	DefaultProjectorMessageIDs                   []int
	ExportCsvEncoding                            *string
	MotionsPreamble                              *string
	DefaultProjectorPollIDs                      []int
	MotionPollDefaultOnehundredPercentBase       *string
	AgendaNumeralSystem                          *string
	ApplauseEnable                               *bool
	JitsiRoomPassword                            *string
	MotionsShowReferringMotions                  *bool
	ConferenceOpenMicrophone                     *bool
	ListOfSpeakersShowAmountOfSpeakersOnSlide    *bool
	UsersPdfWelcometext                          *string
	ForwardedMotionIDs                           []int
	Name                                         string
	PollCandidateIDs                             []int
	UsersPdfWelcometitle                         *string
	MotionsEnableEditor                          *bool
	CustomTranslations                           json.RawMessage
	DefaultProjectorAmendmentIDs                 []int
	EnableAnonymous                              *bool
	LogoProjectorMainID                          *int
	MotionsAmendmentsEnabled                     *bool
	MotionsAmendmentsMultipleParagraphs          *bool
	AssignmentPollEnableMaxVotesPerOption        *bool
	ProjectorIDs                                 []int
	ExportPdfPageMarginLeft                      *int
	TopicIDs                                     []int
	PollBallotPaperSelection                     *string
	PollDefaultOnehundredPercentBase             *string
	AssignmentPollDefaultType                    *string
	ProjectorCountdownDefaultTime                int
	AgendaShowSubtitles                          *bool
	ExportCsvSeparator                           *string
	MotionCategoryIDs                            []int
	ProjectorMessageIDs                          []int
	UserIDs                                      []int
	UsersForbidDelegatorToVote                   *bool
	FontBoldItalicID                             *int
	ListOfSpeakersAmountLastOnProjector          *int
	ListOfSpeakersDefaultStructureLevelTime      *int
	MeetingUserIDs                               []int
	MotionsAmendmentsPrefix                      *string
	PersonalNoteIDs                              []int
	ConferenceAutoConnect                        *bool
	DefaultProjectorAssignmentPollIDs            []int
	MotionsLineLength                            *int
	AssignmentPollBallotPaperNumber              *int
	GroupIDs                                     []int
	LogoPdfHeaderRID                             *int
	MotionEditorIDs                              []int
	MotionChangeRecommendationIDs                []int
	OrganizationTagIDs                           []int
	AssignmentsExportTitle                       *string
	ChatMessageIDs                               []int
	ExportPdfPageMarginBottom                    *int
	IsActiveInOrganizationID                     *int
	ListOfSpeakersPresentUsersOnly               *bool
	LogoWebHeaderID                              *int
	ListOfSpeakersEnableProContraSpeech          *bool
	MotionsSupportersMinAmount                   *int
	UsersEmailBody                               *string
	UsersPdfWlanSsid                             *string
	AgendaItemIDs                                []int
	ConferenceLosRestriction                     *bool
	FontItalicID                                 *int
	MotionPollBallotPaperSelection               *string
	MotionsAmendmentsTextMode                    *string
	MotionsEnableReasonOnProjector               *bool
	MotionsRecommendationsBy                     *string
	AssignmentPollDefaultBackend                 *string
	ExternalID                                   *string
	ListOfSpeakersClosingDisablesPointOfOrder    *bool
	MotionsAmendmentsOfAmendments                *bool
	MotionsReasonRequired                        *bool
	AssignmentsExportPreamble                    *string
	ChatGroupIDs                                 []int
	ImportedAt                                   *int
	ProjectorCountdownIDs                        []int
	ApplauseTimeout                              *int
	DefaultProjectorCountdownIDs                 []int
	ExportPdfPagenumberAlignment                 *string
	MotionCommentSectionIDs                      []int
	MotionsDefaultSorting                        *string
	UsersAllowSelfSetPresent                     *bool
	ConferenceEnableHelpdesk                     *bool
	ConferenceStreamPosterUrl                    *string
	MotionCommentIDs                             []int
	MotionSubmitterIDs                           []int
	AdminGroupID                                 *int
	DefaultProjectorAgendaItemListIDs            []int
	MotionsDefaultWorkflowID                     int
	MotionsEnableSideboxOnProjector              *bool
	DefaultMeetingForCommitteeID                 *int
	DefaultProjectorMotionBlockIDs               []int
	EndTime                                      *int
}

func (m Meeting) CollectionName() string {
	return "meeting"
}
