package models

import "encoding/json"

type Meeting struct {
	AdminGroupID                                 *int
	AgendaEnableNumbering                        *bool
	AgendaItemCreation                           *string
	AgendaItemIDs                                []int
	AgendaNewItemsDefaultVisibility              *string
	AgendaNumberPrefix                           *string
	AgendaNumeralSystem                          *string
	AgendaShowInternalItemsOnProjector           *bool
	AgendaShowSubtitles                          *bool
	AgendaShowTopicNavigationOnDetailView        *bool
	AllProjectionIDs                             []int
	AnonymousGroupID                             *int
	ApplauseEnable                               *bool
	ApplauseMaxAmount                            *int
	ApplauseMinAmount                            *int
	ApplauseParticleImageUrl                     *string
	ApplauseShowLevel                            *bool
	ApplauseTimeout                              *int
	ApplauseType                                 *string
	AssignmentCandidateIDs                       []int
	AssignmentIDs                                []int
	AssignmentPollAddCandidatesToListOfSpeakers  *bool
	AssignmentPollBallotPaperNumber              *int
	AssignmentPollBallotPaperSelection           *string
	AssignmentPollDefaultBackend                 *string
	AssignmentPollDefaultGroupIDs                []int
	AssignmentPollDefaultMethod                  *string
	AssignmentPollDefaultOnehundredPercentBase   *string
	AssignmentPollDefaultType                    *string
	AssignmentPollEnableMaxVotesPerOption        *bool
	AssignmentPollSortPollResultByVotes          *bool
	AssignmentsExportPreamble                    *string
	AssignmentsExportTitle                       *string
	ChatGroupIDs                                 []int
	ChatMessageIDs                               []int
	CommitteeID                                  int
	ConferenceAutoConnect                        *bool
	ConferenceAutoConnectNextSpeakers            *int
	ConferenceEnableHelpdesk                     *bool
	ConferenceLosRestriction                     *bool
	ConferenceOpenMicrophone                     *bool
	ConferenceOpenVideo                          *bool
	ConferenceShow                               *bool
	ConferenceStreamPosterUrl                    *string
	ConferenceStreamUrl                          *string
	CustomTranslations                           json.RawMessage
	DefaultGroupID                               int
	DefaultMeetingForCommitteeID                 *int
	DefaultProjectorAgendaItemListIDs            []int
	DefaultProjectorAmendmentIDs                 []int
	DefaultProjectorAssignmentIDs                []int
	DefaultProjectorAssignmentPollIDs            []int
	DefaultProjectorCountdownIDs                 []int
	DefaultProjectorCurrentListOfSpeakersIDs     []int
	DefaultProjectorListOfSpeakersIDs            []int
	DefaultProjectorMediafileIDs                 []int
	DefaultProjectorMessageIDs                   []int
	DefaultProjectorMotionBlockIDs               []int
	DefaultProjectorMotionIDs                    []int
	DefaultProjectorMotionPollIDs                []int
	DefaultProjectorPollIDs                      []int
	DefaultProjectorTopicIDs                     []int
	Description                                  *string
	EnableAnonymous                              *bool
	EndTime                                      *int
	ExportCsvEncoding                            *string
	ExportCsvSeparator                           *string
	ExportPdfFontsize                            *int
	ExportPdfLineHeight                          *float32
	ExportPdfPageMarginBottom                    *int
	ExportPdfPageMarginLeft                      *int
	ExportPdfPageMarginRight                     *int
	ExportPdfPageMarginTop                       *int
	ExportPdfPagenumberAlignment                 *string
	ExportPdfPagesize                            *string
	ExternalID                                   *string
	FontBoldID                                   *int
	FontBoldItalicID                             *int
	FontChyronSpeakerNameID                      *int
	FontItalicID                                 *int
	FontMonospaceID                              *int
	FontProjectorH1ID                            *int
	FontProjectorH2ID                            *int
	FontRegularID                                *int
	ForwardedMotionIDs                           []int
	GroupIDs                                     []int
	ID                                           *int
	ImportedAt                                   *int
	IsActiveInOrganizationID                     *int
	IsArchivedInOrganizationID                   *int
	JitsiDomain                                  *string
	JitsiRoomName                                *string
	JitsiRoomPassword                            *string
	Language                                     string
	ListOfSpeakersAllowMultipleSpeakers          *bool
	ListOfSpeakersAmountLastOnProjector          *int
	ListOfSpeakersAmountNextOnProjector          *int
	ListOfSpeakersCanCreatePointOfOrderForOthers *bool
	ListOfSpeakersCanSetContributionSelf         *bool
	ListOfSpeakersClosingDisablesPointOfOrder    *bool
	ListOfSpeakersCountdownID                    *int
	ListOfSpeakersCoupleCountdown                *bool
	ListOfSpeakersDefaultStructureLevelTime      *int
	ListOfSpeakersEnableInterposedQuestion       *bool
	ListOfSpeakersEnablePointOfOrderCategories   *bool
	ListOfSpeakersEnablePointOfOrderSpeakers     *bool
	ListOfSpeakersEnableProContraSpeech          *bool
	ListOfSpeakersHideContributionCount          *bool
	ListOfSpeakersIDs                            []int
	ListOfSpeakersInitiallyClosed                *bool
	ListOfSpeakersInterventionTime               *int
	ListOfSpeakersPresentUsersOnly               *bool
	ListOfSpeakersShowAmountOfSpeakersOnSlide    *bool
	ListOfSpeakersShowFirstContribution          *bool
	ListOfSpeakersSpeakerNoteForEveryone         *bool
	Location                                     *string
	LockedFromInside                             *bool
	LogoPdfBallotPaperID                         *int
	LogoPdfFooterLID                             *int
	LogoPdfFooterRID                             *int
	LogoPdfHeaderLID                             *int
	LogoPdfHeaderRID                             *int
	LogoProjectorHeaderID                        *int
	LogoProjectorMainID                          *int
	LogoWebHeaderID                              *int
	MediafileIDs                                 []int
	MeetingMediafileIDs                          []int
	MeetingUserIDs                               []int
	MotionBlockIDs                               []int
	MotionCategoryIDs                            []int
	MotionChangeRecommendationIDs                []int
	MotionCommentIDs                             []int
	MotionCommentSectionIDs                      []int
	MotionEditorIDs                              []int
	MotionIDs                                    []int
	MotionPollBallotPaperNumber                  *int
	MotionPollBallotPaperSelection               *string
	MotionPollDefaultBackend                     *string
	MotionPollDefaultGroupIDs                    []int
	MotionPollDefaultMethod                      *string
	MotionPollDefaultOnehundredPercentBase       *string
	MotionPollDefaultType                        *string
	MotionStateIDs                               []int
	MotionStatuteParagraphIDs                    []int
	MotionSubmitterIDs                           []int
	MotionWorkflowIDs                            []int
	MotionWorkingGroupSpeakerIDs                 []int
	MotionsAmendmentsEnabled                     *bool
	MotionsAmendmentsInMainList                  *bool
	MotionsAmendmentsMultipleParagraphs          *bool
	MotionsAmendmentsOfAmendments                *bool
	MotionsAmendmentsPrefix                      *string
	MotionsAmendmentsTextMode                    *string
	MotionsBlockSlideColumns                     *int
	MotionsDefaultAmendmentWorkflowID            int
	MotionsDefaultLineNumbering                  *string
	MotionsDefaultSorting                        *string
	MotionsDefaultStatuteAmendmentWorkflowID     int
	MotionsDefaultWorkflowID                     int
	MotionsEnableEditor                          *bool
	MotionsEnableReasonOnProjector               *bool
	MotionsEnableRecommendationOnProjector       *bool
	MotionsEnableSideboxOnProjector              *bool
	MotionsEnableTextOnProjector                 *bool
	MotionsEnableWorkingGroupSpeaker             *bool
	MotionsExportFollowRecommendation            *bool
	MotionsExportPreamble                        *string
	MotionsExportSubmitterRecommendation         *bool
	MotionsExportTitle                           *string
	MotionsLineLength                            *int
	MotionsNumberMinDigits                       *int
	MotionsNumberType                            *string
	MotionsNumberWithBlank                       *bool
	MotionsPreamble                              *string
	MotionsReasonRequired                        *bool
	MotionsRecommendationTextMode                *string
	MotionsRecommendationsBy                     *string
	MotionsShowReferringMotions                  *bool
	MotionsShowSequentialNumber                  *bool
	MotionsStatuteRecommendationsBy              *string
	MotionsStatutesEnabled                       *bool
	MotionsSupportersMinAmount                   *int
	Name                                         string
	OptionIDs                                    []int
	OrganizationTagIDs                           []int
	PersonalNoteIDs                              []int
	PointOfOrderCategoryIDs                      []int
	PollBallotPaperNumber                        *int
	PollBallotPaperSelection                     *string
	PollCandidateIDs                             []int
	PollCandidateListIDs                         []int
	PollCountdownID                              *int
	PollCoupleCountdown                          *bool
	PollDefaultBackend                           *string
	PollDefaultGroupIDs                          []int
	PollDefaultMethod                            *string
	PollDefaultOnehundredPercentBase             *string
	PollDefaultType                              *string
	PollIDs                                      []int
	PollSortPollResultByVotes                    *bool
	PresentUserIDs                               []int
	ProjectionIDs                                []int
	ProjectorCountdownDefaultTime                int
	ProjectorCountdownIDs                        []int
	ProjectorCountdownWarningTime                int
	ProjectorIDs                                 []int
	ProjectorMessageIDs                          []int
	ReferenceProjectorID                         int
	SpeakerIDs                                   []int
	StartTime                                    *int
	StructureLevelIDs                            []int
	StructureLevelListOfSpeakersIDs              []int
	TagIDs                                       []int
	TemplateForOrganizationID                    *int
	TopicIDs                                     []int
	TopicPollDefaultGroupIDs                     []int
	UserIDs                                      []int
	UsersAllowSelfSetPresent                     *bool
	UsersEmailBody                               *string
	UsersEmailReplyto                            *string
	UsersEmailSender                             *string
	UsersEmailSubject                            *string
	UsersEnablePresenceView                      *bool
	UsersEnableVoteDelegations                   *bool
	UsersEnableVoteWeight                        *bool
	UsersForbidDelegatorAsSubmitter              *bool
	UsersForbidDelegatorAsSupporter              *bool
	UsersForbidDelegatorInListOfSpeakers         *bool
	UsersForbidDelegatorToVote                   *bool
	UsersPdfWelcometext                          *string
	UsersPdfWelcometitle                         *string
	UsersPdfWlanEncryption                       *string
	UsersPdfWlanPassword                         *string
	UsersPdfWlanSsid                             *string
	VoteIDs                                      []int
	WelcomeText                                  *string
	WelcomeTitle                                 *string
}

func (m Meeting) CollectionName() string {
	return "meeting"
}
