name: main

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23"

      - name: Go Format
        run: gofmt -s -w . && git diff --exit-code

      - name: Go Vet
        run: go vet ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1

      - name: Test
        run: go test -v -count=1 -race -shuffle=on -coverprofile=coverage.txt -json ./... > test.json

      - name: Annotate tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.8.0
        with:
          test-results: test.json
